spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:motulrappi_db}:${RDS_PORT:5432}/MotulRappiDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka

# logging:
#   level:
#     root: DEBUG
