spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:motulrappi_db}:${RDS_PORT:5432}/MotulRappiDB
    username: ${DB_USERNAME:motulrappidb}
    password: ${DB_PASSWORD:motul#rappi@db2024}

logging:
  level:
    root: ERROR