spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/MotulRappiDB
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
# logging:
#   level:
#     root: DEBUG
