spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:motulrappi_db}:${RDS_PORT:5432}/MotulRappiDB
    username: ${DB_USERNAME:MotulRappiUser}
    password: ${DB_PASSWORD:Motu1#R4ppI@2024}

logging:
  level:
    root: ERROR