spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:motulrappi_db}:${RDS_PORT:5432}/MotulRappiDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    root: ERROR