spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:prod-db-host}:${RDS_PORT:5432}/MotulRappiDB
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:prod_pass}

logging:
  level:
    root: ERROR