spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:motulrappi_db}:${RDS_PORT:5432}/MotulRappiDB
    username: ${DB_USERNAME:motulrappidb}
    password: ${DB_PASSWORD:motul#rappi@db2024}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev