server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    instance:
      instance-id: ${spring.application.name}:${server.port}

#application:
#  security:
#    jwt:
#      expiration: 86400000
#      refresh-token:
#        expiration: 604800000

