server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    instance:
      instance-id: ${spring.application.name}:${server.port}

application:
  security:
    jwt:
      expiration: ${JWT_EXPIRATION:86400000}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000}