spring:
  application:
    name: authentication-microservice

server:
  port: ${PORT:${SERVER_PORT:8080}}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
  
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

application:
  security:
    jwt:
      expiration: ${JWT_EXPIRATION:86400000}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000}