server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: AUTHENTICATION-MICROSERVICE
          uri: lb://AUTHENTICATION-MICROSERVICE/
          predicates:
            - Path=/auth/**
          filters:
            - name: AuthFilter
              args:
                excludePaths: /auth/login,/auth/validate,/auth/validateWithRequest,/auth/forgotPassword/verifyMail/**
        - id: LOCATIONS-MICROSERVICE
          uri: lb://LOCATIONS-MICROSERVICE/
          predicates:
            - Path=/location/**
          filters:
            - name: AuthFilter
              args:
                excludePaths: /location/public
        - id: PRODUCTS-MICROSERVICE
          uri: lb://PRODUCTS-MICROSERVICE/
          predicates:
            - Path=/product/**
          filters:
            - AuthFilter
        - id: PROMOTIONS-MICROSERVICE
          uri: lb://PROMOTIONS-MICROSERVICE/
          predicates:
            - Path=/promotion/**
          filters:
            - AuthFilter
        - id: RAPPICOURIERS-MICROSERVICE
          uri: lb://RAPPICOURIERS-MICROSERVICE/
          predicates:
            - Path=/rappiCourier/**
          filters:
            - name: AuthFilter
              args:
                excludePaths: /rappiCourier/public
        - id: REGISTER-PROMOTIONS-MICROSERVICE
          uri: lb://REGISTER-PROMOTIONS-MICROSERVICE/
          predicates:
            - Path=/registerPromotion/**
          filters:
            - AuthFilter
        - id: COMMERCE-MICROSERVICE
          uri: lb://COMMERCE-MICROSERVICE/
          predicates:
            - Path=/commerce/**
          filters:
            - AuthFilter
        - id: ADMIN-MICROSERVICE
          uri: lb://ADMIN-MICROSERVICE/
          predicates:
            - Path=/admin/**
          filters:
            - AuthFilter

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka

  instance:
    hostname: localhost